// Xe35 (CRI) shim TU for the plain bf16 MoE grouped GEMM.
// Links against the AOT-compiled launcher instances generated by
// src/GroupGemmXe35.cmake for SYCL_INTEL_TARGET=35.
#define SYCL_INTEL_TARGET 35

#include "../kernels/moe/xe35/GroupGemm.hpp"

#undef SYCL_INTEL_TARGET
