/***************************************************************************************************
 * Copyright (C) 2026 Intel Corporation, All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/
/*! \file
    \brief MLA decode dispatch interface for PyTorch.
    Heavy template instantiations are compiled in separate per-kernel
    compilation units generated by MlaDecodeXe20.cmake.
*/
#define SYCL_INTEL_TARGET 20
#include <ATen/ATen.h>
#include <c10/xpu/XPUStream.h>
#include <torch/all.h>

#include <sycl/sycl.hpp>

#include "Utils.h"
#include "sycl/kernels/mla/device/mla_decode_dispatch.hpp"
#include "sycl/kernels/mla/device/mla_decode_types.hpp"

namespace {

/// Compute optimal split-KV count based on page_size and base parallelism.
///
/// Derived from exhaustive tests on BMG :
///   - batch_size: 1, 4, 16
///   - seq_len: 1024, 2048, 4096, 8192
///   - num_heads: 16, 32, 64, 128
///   - page_size: 16, 32, 64, 128
///   - num_kv_splits: 1, 2, 4, 8, 10, 16, 20, 24, 30, 36, 48, 64
/// TODO: find a same optimal kv_split formula (ref:src/sycl/flash_attention.cpp[get_num_splits]), when entire mla is
/// optimized.
int64_t set_split_kv(int64_t batch, int64_t num_heads_q, int64_t seq_len_kv, int64_t page_size) {
  int base_parallel = batch * num_heads_q;
  int total_pages = (seq_len_kv + page_size - 1) / page_size;

  int kv_per_split;
  if (page_size <= 16) {
    kv_per_split = (base_parallel <= 64) ? 256 : 128;
  } else if (page_size <= 32) {
    kv_per_split = (base_parallel <= 64) ? 192 : 64;
  } else if (page_size <= 64) {
    kv_per_split = (base_parallel <= 64) ? 128 : 64;
  } else {
    kv_per_split = page_size;
  }

  int pages_per_split = std::max(1, kv_per_split / static_cast<int>(page_size));
  int num_splits = std::max(1, total_pages / pages_per_split);
  num_splits = std::min(num_splits, total_pages);

  if (batch == 1 && num_heads_q > total_pages) {
    int ratio = static_cast<int>(num_heads_q) / total_pages;
    int capped_splits = std::max(2, num_splits / ratio);
    num_splits = std::min(num_splits, capped_splits);
  }

  return std::max(1, num_splits);
}

#define DISPATCH_MLA_PAGE_SIZE(ELEM)                                                                           \
  do {                                                                                                         \
    switch (page_size) {                                                                                       \
      case 16:                                                                                                 \
        mla_decode::launch_mla_decode_##ELEM##_16(                                                             \
            out, q_nope, q_pe, kv_c_and_k_pe_cache, seq_lens, page_table, workspace, sm_scale, num_kv_splits); \
        break;                                                                                                 \
      case 32:                                                                                                 \
        mla_decode::launch_mla_decode_##ELEM##_32(                                                             \
            out, q_nope, q_pe, kv_c_and_k_pe_cache, seq_lens, page_table, workspace, sm_scale, num_kv_splits); \
        break;                                                                                                 \
      case 64:                                                                                                 \
        mla_decode::launch_mla_decode_##ELEM##_64(                                                             \
            out, q_nope, q_pe, kv_c_and_k_pe_cache, seq_lens, page_table, workspace, sm_scale, num_kv_splits); \
        break;                                                                                                 \
      case 128:                                                                                                \
        mla_decode::launch_mla_decode_##ELEM##_128(                                                            \
            out, q_nope, q_pe, kv_c_and_k_pe_cache, seq_lens, page_table, workspace, sm_scale, num_kv_splits); \
        break;                                                                                                 \
      default:                                                                                                 \
        TORCH_CHECK(false, "Unsupported page size for MLA decode: ", page_size);                               \
    }                                                                                                          \
  } while (0)

#define DISPATCH_MLA_DTYPE()                                              \
  do {                                                                    \
    switch (in_dtype) {                                                   \
      case at::ScalarType::Half:                                          \
        DISPATCH_MLA_PAGE_SIZE(half);                                     \
        break;                                                            \
      case at::ScalarType::BFloat16:                                      \
        DISPATCH_MLA_PAGE_SIZE(bf16);                                     \
        break;                                                            \
      default:                                                            \
        TORCH_CHECK(false, "Unsupported input data type for MLA decode"); \
    }                                                                     \
  } while (0)
}  // namespace

/// @brief Dispatch kernel implementation for MLA decode.
void flash_mla_decode(
    at::Tensor& out,                        // (batch, num_heads, latent_dim)
    const at::Tensor& q_nope,               // (batch, num_heads, latent_dim)
    const at::Tensor& q_pe,                 // (batch, num_heads, rope_dim)
    const at::Tensor& kv_c_and_k_pe_cache,  // (total_no_of_pages, page_size, (latent_dim + rope_dim))
    const at::Tensor& seq_lens,             // (batch_size,)
    const at::Tensor& page_table,           // (batch_size, max_num_pages_per_seq)
    at::Tensor& workspace,
    double sm_scale,  // softmax scale
    int64_t num_kv_splits) {
  CHECK_INPUT(out);
  CHECK_INPUT(q_nope);
  CHECK_INPUT(q_pe);
  CHECK_INPUT(kv_c_and_k_pe_cache);
  CHECK_INPUT(seq_lens);
  CHECK_INPUT(page_table);
  CHECK_INPUT(workspace);

  int page_size = kv_c_and_k_pe_cache.size(1);

  c10::DeviceGuard guard(q_nope.device());

  auto in_dtype = q_nope.scalar_type();

  TORCH_CHECK(
      in_dtype == at::ScalarType::Half || in_dtype == at::ScalarType::BFloat16,
      "Unsupported input data type for MLA decode");
  TORCH_CHECK(
      page_size == 16 || page_size == 32 || page_size == 64 || page_size == 128,
      "Unsupported page size for MLA decode: ",
      page_size,
      ". Supported: 16, 32, 64, 128");

  if (num_kv_splits < 1) {
    int page_count_per_seq = page_table.size(1);
    int max_seq_len = page_size * page_count_per_seq;
    num_kv_splits = set_split_kv(q_nope.size(0), q_nope.size(1), max_seq_len, page_size);
  }

  DISPATCH_MLA_DTYPE();
}

#undef DISPATCH_MLA_PAGE_SIZE
#undef DISPATCH_MLA_DTYPE

namespace {
template <typename MlaXeType>
int64_t mla_workspace_size(int64_t num_batches, int64_t num_heads, int64_t num_kv_splits) {
  typename MlaXeType::Fmla::Arguments args{};
  args.kernel.shape.batch = num_batches;
  args.kernel.shape.num_heads_q = num_heads;
  args.kernel.shape.head_size_o = 512;
  args.split_kv = num_kv_splits;
  return MlaXeType::Fmla::get_workspace_size(args);
}
}  // namespace

int64_t flash_mla_get_workspace_size(
    int64_t max_seq_len, int64_t num_batches, int64_t num_heads, int64_t page_size, int64_t num_kv_splits) {
  if (num_kv_splits < 1) {
    TORCH_CHECK(num_heads > 0, "num_heads must be > 0 when num_kv_splits is auto-selected");
    TORCH_CHECK(
        page_size == 16 || page_size == 32 || page_size == 64 || page_size == 128,
        "Unsupported page size: ",
        page_size);
    num_kv_splits = set_split_kv(num_batches, num_heads, max_seq_len, page_size);
  }
  if (num_kv_splits == 1) {
    return 0;
  } else {
    switch (page_size) {
      case 16:
        return mla_workspace_size<MlaXe<cutlass::half_t, PageSizeOption<16>, EnabledSplitKV<true>>>(
            num_batches, num_heads, num_kv_splits);
      case 32:
        return mla_workspace_size<MlaXe<cutlass::half_t, PageSizeOption<32>, EnabledSplitKV<true>>>(
            num_batches, num_heads, num_kv_splits);
      case 64:
        return mla_workspace_size<MlaXe<cutlass::half_t, PageSizeOption<64>, EnabledSplitKV<true>>>(
            num_batches, num_heads, num_kv_splits);
      case 128:
        return mla_workspace_size<MlaXe<cutlass::half_t, PageSizeOption<128>, EnabledSplitKV<true>>>(
            num_batches, num_heads, num_kv_splits);
      default:
        TORCH_CHECK(false, "Unsupported page size: ", page_size);
        return 0;
    }
  }
}

#undef SYCL_INTEL_TARGET
