/***************************************************************************************************
 * Copyright (C) 2026 Intel Corporation, All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/
/*! \file
    \brief MLA prefill dispatch interface for PyTorch.

    Accepts ragged/varlen Q tensors (total_q, num_heads, dim) with cu_seqlens_q.
    Supports incremental prefill with causal masking:
    prefix tokens are unmasked, only new prompt tokens get triangular mask.

    Heavy template instantiations are compiled in separate per-kernel
    compilation units generated by MlaPrefillXe20.cmake.
*/
#define SYCL_INTEL_TARGET 20
#include <ATen/ATen.h>
#include <c10/xpu/XPUStream.h>
#include <torch/all.h>

#include <sycl/sycl.hpp>

#include "Utils.h"
#include "sycl/kernels/mla/device/mla_decode_types.hpp"  // MlaXe workspace helper
#include "sycl/kernels/mla/device/mla_prefill_dispatch.hpp"
#include "sycl/kernels/mla/device/mla_prefill_types.hpp"

namespace {

// Host-side 2D (Q, K) tile-bucket dispatch. Selects the small-tile kernel
// (Q_TILE_M=32, NumSubgroupsM=4) vs the large-tile kernel (Q_TILE_M=256,
// NumSubgroupsM=32). The large bucket only wins when BOTH axes are
// large enough to amortize its per-WG launch + prologue overhead and
// fill the 256-row Q tile cleanly.
//
// Empirically tuned on BMG via benchmark/bench_flash_mla_prefill.py.
// Re-tuned Jun 18 (post medium-bucket validation on granular2 sweep):
//   - Q < 192: small wins (bandwidth-bound regime; MLA's latent-KV
//     advantage dominates; medium would pay 50-75% padding waste at
//     small Q. Q=64 small bucket achieves best throughput; medium drops
//     ~35% at small Q).
//   - 192 <= Q < 512, ANY K: medium wins. Closes the cliff at Q in
//     {255, 256, 448} (small pays Q-tile padding waste). Also captures the
//     Q-tile-misfit wins at Q in {320, 384} K >= 1024 where medium
//     beats large by 23-27% (large pays 25-37% padding rounding to
//     Q_TILE_M=256; medium fits 128-row tiles cleanly).
//   - Q >= 512, K < 1024: medium wins. Per-WG fixed cost amortizes
//     better than large at low K-iter count (large rejected by the
//     prior kKThresholdForLarge=512 probe).
//   - Q >= 512, K >= 1024: large wins. Compute-heavy regime; large's
//     32-SG/WG amortization across many K-iters dominates.
//
// max_kv_len_estimate uses page_table.size(1) * page_size: SGLang sizes
// the page-table column to ceil(max_seq_k / page_size), so this is a
// tight upper bound on max KV length without a device->host sync.
constexpr int kQTileSmallThreshold = 192;  // Q < this -> small bucket
constexpr int kQTileLargeThreshold = 512;  // Q >= this AND K >= K_thld -> large
constexpr int kKThresholdForLarge = 1024;  // K split point: medium vs large for Q >= 512

// Diagnostic dispatch override (paired with ABLATE_KPE_FULL experiments).
// 0 = honor (Q,K) thresholds (production behavior, binary small/large).
// 1 = force large bucket  regardless of Q/K.
// 2 = force small bucket  regardless of Q/K.
// 3 = force medium bucket regardless of Q/K  (no production predicate yet
//     -- the medium bucket is currently force-only; we gate adding a
//     3-way predicate on empirical force-medium measurements).
// MUST be 0 for any shippable build.
#define MLA_FORCE_DISPATCH 0

#define DISPATCH_MLA_PREFILL_PAGE_SIZE(ELEM, BUCKET)                              \
  do {                                                                            \
    switch (page_size) {                                                          \
      case 16:                                                                    \
        mla_prefill::launch_mla_prefill_##ELEM##_16_##BUCKET(                     \
            out,                                                                  \
            q_nope,                                                               \
            q_pe,                                                                 \
            kv_c_and_k_pe_cache,                                                  \
            cu_seqlens_q,                                                         \
            seq_lens,                                                             \
            max_seqlen_q,                                                         \
            page_table,                                                           \
            workspace,                                                            \
            sm_scale,                                                             \
            causal,                                                               \
            num_kv_splits);                                                       \
        break;                                                                    \
      case 32:                                                                    \
        mla_prefill::launch_mla_prefill_##ELEM##_32_##BUCKET(                     \
            out,                                                                  \
            q_nope,                                                               \
            q_pe,                                                                 \
            kv_c_and_k_pe_cache,                                                  \
            cu_seqlens_q,                                                         \
            seq_lens,                                                             \
            max_seqlen_q,                                                         \
            page_table,                                                           \
            workspace,                                                            \
            sm_scale,                                                             \
            causal,                                                               \
            num_kv_splits);                                                       \
        break;                                                                    \
      case 64:                                                                    \
        mla_prefill::launch_mla_prefill_##ELEM##_64_##BUCKET(                     \
            out,                                                                  \
            q_nope,                                                               \
            q_pe,                                                                 \
            kv_c_and_k_pe_cache,                                                  \
            cu_seqlens_q,                                                         \
            seq_lens,                                                             \
            max_seqlen_q,                                                         \
            page_table,                                                           \
            workspace,                                                            \
            sm_scale,                                                             \
            causal,                                                               \
            num_kv_splits);                                                       \
        break;                                                                    \
      case 128:                                                                   \
        mla_prefill::launch_mla_prefill_##ELEM##_128_##BUCKET(                    \
            out,                                                                  \
            q_nope,                                                               \
            q_pe,                                                                 \
            kv_c_and_k_pe_cache,                                                  \
            cu_seqlens_q,                                                         \
            seq_lens,                                                             \
            max_seqlen_q,                                                         \
            page_table,                                                           \
            workspace,                                                            \
            sm_scale,                                                             \
            causal,                                                               \
            num_kv_splits);                                                       \
        break;                                                                    \
      default:                                                                    \
        TORCH_CHECK(false, "Unsupported page size for MLA prefill: ", page_size); \
    }                                                                             \
  } while (0)

#define DISPATCH_MLA_PREFILL_DTYPE(BUCKET)                                 \
  do {                                                                     \
    switch (in_dtype) {                                                    \
      case at::ScalarType::Half:                                           \
        DISPATCH_MLA_PREFILL_PAGE_SIZE(half, BUCKET);                      \
        break;                                                             \
      case at::ScalarType::BFloat16:                                       \
        DISPATCH_MLA_PREFILL_PAGE_SIZE(bf16, BUCKET);                      \
        break;                                                             \
      default:                                                             \
        TORCH_CHECK(false, "Unsupported input data type for MLA prefill"); \
    }                                                                      \
  } while (0)

}  // namespace

/// @brief Dispatch kernel for MLA prefill with varlen/ragged Q and causal mask.
void flash_mla_prefill(
    at::Tensor& out,                        // (total_q, num_heads, latent_dim)
    const at::Tensor& q_nope,               // (total_q, num_heads, latent_dim)
    const at::Tensor& q_pe,                 // (total_q, num_heads, rope_dim)
    const at::Tensor& kv_c_and_k_pe_cache,  // (total_pages, page_size, latent_dim + rope_dim)
    const at::Tensor& cu_seqlens_q,         // (batch + 1,) cumulative Q lengths
    const at::Tensor& seq_lens,             // (batch,) actual KV length per batch item
    int64_t max_seqlen_q,
    const at::Tensor& page_table,  // (batch, max_pages_per_seq)
    at::Tensor& workspace,
    double sm_scale,
    bool causal,
    int64_t num_kv_splits) {
  CHECK_INPUT(out);
  CHECK_INPUT(q_nope);
  CHECK_INPUT(q_pe);
  CHECK_INPUT(kv_c_and_k_pe_cache);
  CHECK_INPUT(cu_seqlens_q);
  CHECK_INPUT(seq_lens);
  CHECK_INPUT(page_table);
  CHECK_INPUT(workspace);

  int page_size = kv_c_and_k_pe_cache.size(1);

  c10::DeviceGuard guard(q_nope.device());

  auto in_dtype = q_nope.scalar_type();

  TORCH_CHECK(num_kv_splits <= 1, "Manual KV splits are not supported yet.");
  TORCH_CHECK(causal, "Non-causal MLA prefill is not supported yet.");
  TORCH_CHECK(
      in_dtype == at::ScalarType::Half || in_dtype == at::ScalarType::BFloat16,
      "Unsupported input data type for MLA prefill");
  TORCH_CHECK(
      page_size == 16 || page_size == 32 || page_size == 64 || page_size == 128,
      "Unsupported page size for MLA prefill: ",
      page_size,
      ". Supported: 16, 32, 64, 128");
  TORCH_CHECK(q_nope.dim() == 3, "q_nope must be 3D (total_q, num_heads, dim), got ", q_nope.dim());
  TORCH_CHECK(q_pe.dim() == 3, "q_pe must be 3D (total_q, num_heads, dim), got ", q_pe.dim());

  const int64_t max_kv_len_estimate = page_table.size(1) * page_size;

  // 3-way bucket selection (predicate B from Jun 18 granular2 force-medium
  // sweep): Q < 192 -> small; Q in [192, 512) -> medium for any K;
  // Q >= 512 -> large iff K >= 1024 else medium.
  enum class Bucket { Small, Medium, Large };
#if MLA_FORCE_DISPATCH == 1
  const Bucket bucket = Bucket::Large;
#elif MLA_FORCE_DISPATCH == 2
  const Bucket bucket = Bucket::Small;
#elif MLA_FORCE_DISPATCH == 3
  const Bucket bucket = Bucket::Medium;
#else
  Bucket bucket;
  if (max_seqlen_q < kQTileSmallThreshold) {
    bucket = Bucket::Small;
  } else if (max_seqlen_q >= kQTileLargeThreshold && max_kv_len_estimate >= kKThresholdForLarge) {
    bucket = Bucket::Large;
  } else {
    bucket = Bucket::Medium;
  }
#endif

  switch (bucket) {
    case Bucket::Large:
      DISPATCH_MLA_PREFILL_DTYPE(large);
      break;
    case Bucket::Medium:
      DISPATCH_MLA_PREFILL_DTYPE(medium);
      break;
    case Bucket::Small:
      DISPATCH_MLA_PREFILL_DTYPE(small);
      break;
  }
}

#undef DISPATCH_MLA_PREFILL_PAGE_SIZE
#undef DISPATCH_MLA_PREFILL_DTYPE

/// @brief Workspace size for MLA prefill (currently 0 – no split-K).
/// Signature mirrors flash_mla_get_workspace_size for caller ergonomics; on XPU
/// the device sm_count is queried internally, so callers don't pass it.
int64_t flash_mla_prefill_get_workspace_size(
    int64_t /*max_seq_len*/,
    int64_t /*num_batches*/,
    int64_t /*num_heads*/,
    int64_t /*page_size*/,
    int64_t /*num_kv_splits*/) {
  using MlaXePrefillType = MlaXePrefill<sycl::half>;
  typename MlaXePrefillType::Fmla::Arguments arguments;
  return MlaXePrefillType::Fmla::get_workspace_size(arguments);
}

#undef SYCL_INTEL_TARGET
