/***************************************************************************************************
 * Copyright (C) 2026 Intel Corporation, All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/
/*!
  \file
  \brief The runChunkedSgmvLoraShrink<T, TileOpt>() one-shot entry.

  This runner drives the LoRA-A "shrink" grouped GEMM (D = A @ B^T, alpha=1,
  beta=0) end to end for the chunked-SGMV decode path. It is identical in
  structure to sgemm_lora_a_fwd's runner but lives in its own namespace and is
  instantiated on the small-N tile in chunked_sgmv_lora_shrink_types.hpp, so the
  merged sgemm_lora_a_fwd kernel is not touched.

  The heavy CUTLASS type assembly + lifecycle (can_implement / get_workspace_size
  / initialize / run) and the device-side metadata build live in the shared,
  reusable core (group_gemm_types.hpp + grouped_gemm_meta.hpp +
  group_gemm_lora_launcher.hpp). Only the tile axis
  (chunked_sgmv_lora_shrink_types.hpp) differs.
*/

#pragma once

#include <ATen/ATen.h>
#include <torch/all.h>

#include <sycl/sycl.hpp>

#include "cutlass/cutlass.h"
#include "sycl/kernels/lora/common/group_gemm_types.hpp"
#include "sycl/kernels/lora/common/grouped_gemm_meta.hpp"
#include "sycl/kernels/lora/device/chunked_sgmv_lora_shrink_types.hpp"

namespace chunked_sgmv_lora_shrink_impl {

// Drive one pointer-array grouped GEMM (alpha=1, beta=0 => D = A @ B^T) from a
// prebuilt GroupedGemmMeta and the A/B/D base tensors.
template <typename Types>
inline void launchGroupedShrinkGemm(
    const at::native::xpu::GroupedGemmMeta& meta,
    const torch::Tensor& a_base,
    const torch::Tensor& b_base,
    const torch::Tensor& d_base,
    const int num_groups,
    sycl::queue& queue) {
  namespace core = at::native::xpu;
  auto a_ptrs = core::make_device_ptrs(a_base, meta.a_off, queue);
  auto b_ptrs = core::make_device_ptrs(b_base, meta.b_off, queue);
  auto d_ptrs = core::make_device_ptrs(d_base, meta.d_off, queue);

  auto args = core::args_from_options<Types>(
      meta.problem_sizes,
      a_ptrs,
      b_ptrs,
      /*c_ptrs   =*/d_ptrs,  // beta=0 -> C reads are inert
      d_ptrs,
      meta.stride_A,
      meta.stride_B,
      /*stride_C =*/meta.stride_D,
      meta.stride_D,
      num_groups,
      /*alpha    =*/1.0f,
      /*beta     =*/0.0f);

  typename Types::Gemm launcher;

  cutlass::Status status = launcher.can_implement(args);
  TORCH_CHECK(
      status == cutlass::Status::kSuccess,
      "runChunkedSgmvLoraShrink: can_implement failed: status=",
      cutlassGetStatusString(status));

  const size_t workspace_size = Types::Gemm::get_workspace_size(args);
  auto workspace_opts = torch::TensorOptions().dtype(torch::kUInt8).device(d_base.device());
  auto workspace = torch::empty({static_cast<int64_t>(workspace_size)}, workspace_opts);

  status = launcher.run(args, workspace.data_ptr(), queue);
  TORCH_CHECK(
      status == cutlass::Status::kSuccess,
      "runChunkedSgmvLoraShrink: run failed: status=",
      cutlassGetStatusString(status));
}

//----------------- runChunkedSgmvLoraShrink (one-shot entry) ----------------//
// High-level entry called from the per-(dtype, tile) .cpp files generated by
// ChunkedSgmvLoraShrinkXe20.cmake. Builds the pointer-array grouped-GEMM
// metadata on device (one thread per segment), assembles the CUTLASS Arguments
// via args_from_options(), and drives the shared GroupGemmLoraFwd launcher with
// the tile config from TileOpt and (alpha=1, beta=0) for the pure D = A @ B^T of
// the LoRA-A shrink -- one coalesced grouped GEMM straight into output.
//
// The input rows are expected to already be in logical (adapter-grouped) order:
// the caller (ChunkedSgmvLoraShrink.cpp) gathers them there before this runs.
template <typename T, typename TileOpt>
inline void runChunkedSgmvLoraShrink(
    const torch::Tensor& input_x,
    const torch::Tensor& weights,
    const torch::Tensor& seg_indptr_i32,
    const torch::Tensor& weight_indices_i32,
    torch::Tensor& output,
    const int stack_num,
    const int max_rank,
    const int num_segments,
    sycl::queue& queue) {
  namespace core = at::native::xpu;
  using Types = typename TileOpt::template Types<T>;

  const int K = static_cast<int>(input_x.size(1));  // input_dim
  const int N = stack_num * max_rank;               // output columns
  const int64_t elem_bytes = static_cast<int64_t>(sizeof(T));
  const auto device = input_x.device();

  auto meta = core::build_grouped_gemm_meta(
      seg_indptr_i32, weight_indices_i32, N, K, num_segments, elem_bytes, device, queue);
  launchGroupedShrinkGemm<Types>(meta, input_x, weights, output, num_segments, queue);
}

}  // namespace chunked_sgmv_lora_shrink_impl
