/***************************************************************************************************
 * Copyright (C) 2026 Intel Corporation, All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/
/*!
  \file
  \brief The runChunkedSgmvLoraExpandFwd<T, TileOpt>() one-shot entry for the
         chunked-SGMV LoRA-B "expand" grouped GEMM.

  This runner drives the LoRA-B "expand" projection (D = alpha[l] * (A @ B^T) +
  beta * C) for the chunked-SGMV path. It is the generic n_slices sibling of the
  fused QKV / gate-up LoRA-B runners: each input segment s emits num_slices
  groups (one per stacked projection), and the per-slice output-column bands come
  from a caller-supplied slice_offsets table (rather than the hardwired q/k/v or
  gate/up partition). n_slices == 1 is the plain single-projection expand.

  The per-group problem sizes, strides, and byte offsets are built on device by
  the shared, sliced build_grouped_gemm_meta() (common/grouped_gemm_meta.hpp):
  A is the packed [num_tokens, num_slices*K] shrink output (a_row_stride =
  num_slices*K, a_slice_stride = K); B is [num_loras, N_total, K]; the output
  bands come from slice_offsets.

  The epilogue matches SGEMM / QKV / gate-up LoRA-B exactly:
    * D = alpha[group] * (A @ B^T) + beta * C, where alpha[group] = scalings[l]
      is a *per-group* scalar built into meta.alpha and wired into the fusion's
      alpha_ptr_array path by args_from_options().
    * When base_output is supplied it becomes the residual source C with beta=1
      (D = scalings[l] * (A @ B^T) + base_output). base_output shares output's
      [num_tokens, N_total] layout, so the per-group byte offsets (meta.d_off)
      apply to it verbatim. Otherwise beta=0 and C is aliased to D (inert reads).

  The rows are expected to already be in logical (adapter-grouped) order: the
  caller (ChunkedSgmvLoraExpandFwd.cpp) gathers input_x (and base_output) there
  before this runs and scatters the result back afterwards.

  The heavy CUTLASS type assembly + lifecycle live in the shared, reusable core
  (group_gemm_lora_launcher.hpp / common/group_gemm_types.hpp); the tile axis
  lives in chunked_sgmv_lora_expand_fwd_types.hpp.
*/

#pragma once

#include <ATen/ATen.h>
#include <torch/all.h>

#include <optional>
#include <sycl/sycl.hpp>

#include "cutlass/cutlass.h"
#include "sycl/kernels/lora/common/group_gemm_types.hpp"
#include "sycl/kernels/lora/common/grouped_gemm_meta.hpp"
#include "sycl/kernels/lora/device/chunked_sgmv_lora_expand_fwd_types.hpp"

namespace chunked_sgmv_lora_expand_fwd_impl {

//----------------- runChunkedSgmvLoraExpandFwd (one-shot entry) -------------//
// High-level entry called from the per-(dtype, tile) .cpp files generated by
// ChunkedSgmvLoraExpandFwdXe20.cmake. Builds the sliced pointer-array grouped-GEMM
// metadata on device (num_slices * num_segments groups, including the per-group
// alpha buffer from scalings), assembles the CUTLASS Arguments via
// args_from_options(), and drives the shared GroupGemmLoraFwd launcher.
template <typename T, typename TileOpt>
inline void runChunkedSgmvLoraExpandFwd(
    const torch::Tensor& input_x,                     // [num_tokens, num_slices*K]  (K = max_rank)
    const torch::Tensor& weights,                     // [num_loras, N_total, K]
    const torch::Tensor& slice_offsets_i32,           // [num_slices + 1] output-column boundaries
    const torch::Tensor& seg_indptr_i32,              // [num_segments + 1]
    const torch::Tensor& weight_indices_i32,          // [num_segments]
    const torch::Tensor& scalings,                    // [num_loras] fp32 per-adapter scaling (lora_alpha / rank)
    torch::Tensor& output,                            // [num_tokens, N_total]
    const std::optional<torch::Tensor>& base_output,  // [num_tokens, N_total] residual C, or nullopt
    const int N_total,
    const int num_slices,
    const int num_segments,
    sycl::queue& queue) {
  namespace core = at::native::xpu;
  using Types = typename TileOpt::template Types<T>;

  const int K = static_cast<int>(input_x.size(1) / num_slices);  // reduction dim == max_rank
  const int num_groups = num_slices * num_segments;
  const int64_t elem_bytes = static_cast<int64_t>(sizeof(T));
  const auto device = input_x.device();

  // Per-group metadata + alpha (alpha[g] = scalings[weight_indices[g/num_slices]])
  // built on device (one thread per group) via the shared sliced build. Each
  // input_x row is [num_tokens, num_slices*K] so A's leading dim is num_slices*K
  // and projection p reads the K-wide column band at p*K; the per-projection
  // output bands come from slice_offsets. See common/grouped_gemm_meta.hpp.
  auto meta = core::build_grouped_gemm_meta(
      seg_indptr_i32,
      weight_indices_i32,
      N_total,
      K,
      num_segments,
      elem_bytes,
      device,
      queue,
      scalings,
      slice_offsets_i32,
      /*n_slices       =*/num_slices,
      /*a_row_stride   =*/static_cast<int64_t>(num_slices) * K,
      /*a_slice_stride =*/static_cast<int64_t>(K));

  auto a_ptrs = core::make_device_ptrs(input_x, meta.a_off, queue);
  auto b_ptrs = core::make_device_ptrs(weights, meta.b_off, queue);
  auto d_ptrs = core::make_device_ptrs(output, meta.d_off, queue);

  // Per-group alpha as an array-of-pointers: entry g points at meta.alpha[g].
  // The grouped fusion reads *(alpha_ptr_array[l_coord]) with no stride -- the
  // per-group mechanism from upstream 04_bmg_grouped_gemm. Reuse make_device_ptrs:
  // base = meta.alpha, byte offsets = g * sizeof(float).
  auto opt_i64 = torch::TensorOptions().dtype(torch::kInt64).device(device);
  auto alpha_off = torch::arange(num_groups, opt_i64) * static_cast<int64_t>(sizeof(float));
  auto alpha_ptrs = core::make_device_ptrs(meta.alpha, alpha_off, queue);

  // Residual source C. base_output shares output's [num_tokens, N_total] layout,
  // so the per-group byte offsets (meta.d_off) apply verbatim. When absent, beta=0
  // and C is aliased to D so the (inert) C reads touch valid memory.
  const bool has_residual = base_output.has_value();
  const float beta = has_residual ? 1.0f : 0.0f;
  auto c_ptrs = has_residual ? core::make_device_ptrs(*base_output, meta.d_off, queue) : d_ptrs;

  // Build the CUTLASS Arguments (args_from_options). alpha is per-group via the
  // alpha_ptr_array (one pointer per group into meta.alpha); the scalar `alpha`
  // arg is therefore unused and passed as 1.0f.
  auto args = core::args_from_options<Types>(
      meta.problem_sizes,
      a_ptrs,
      b_ptrs,
      c_ptrs,
      d_ptrs,
      meta.stride_A,
      meta.stride_B,
      /*stride_C =*/meta.stride_D,
      meta.stride_D,
      num_groups,
      /*alpha           =*/1.0f,
      /*beta            =*/beta,
      /*alpha_ptr_array =*/alpha_ptrs);

  typename Types::Gemm launcher;

  cutlass::Status status = launcher.can_implement(args);
  TORCH_CHECK(
      status == cutlass::Status::kSuccess,
      "runChunkedSgmvLoraExpandFwd: can_implement failed: status=",
      cutlassGetStatusString(status));

  const size_t workspace_size = Types::Gemm::get_workspace_size(args);
  auto workspace_opts = torch::TensorOptions().dtype(torch::kUInt8).device(device);
  auto workspace = torch::empty({static_cast<int64_t>(workspace_size)}, workspace_opts);

  status = launcher.run(args, workspace.data_ptr(), queue);
  TORCH_CHECK(
      status == cutlass::Status::kSuccess,
      "runChunkedSgmvLoraExpandFwd: run failed: status=",
      cutlassGetStatusString(status));
}

}  // namespace chunked_sgmv_lora_expand_fwd_impl
