/***************************************************************************************************
 * Copyright (C) 2026 Intel Corporation, All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/
/*!
  \file
  \brief The runGateUpLoraBFwd<T, TileOpt>() one-shot entry for the fused gate/up
         LoRA-B forward.

  This runner unpacks a tile option tag (defined in gate_up_lora_b_fwd_types.hpp)
  into the template parameters of the shared pointer-array grouped-GEMM core and
  drives it end to end. It packs two GEMMs (gate / up) per input segment into a
  single grouped GEMM of 2 * num_segments groups; the per-group problem sizes,
  strides, and byte offsets are built on device by the shared, sliced
  build_grouped_gemm_meta() (common/grouped_gemm_meta.hpp) -- gate/up supplies
  n_slices = 2, the uniform [0, N, 2N] output_offset, and the packed-A strides.

  Unlike QKV (variable per-projection N), gate and up share the same output width
  N and the same rank K, so the projection column bands are the uniform partition
  [0, N, 2N]. That offset is derived here on device from output_dim (arange * N)
  rather than passed by the caller, keeping the public gate_up_lora_b_fwd API free
  of an output_offset argument.

  The epilogue matches SGEMM / QKV LoRA-B exactly:
    * D = alpha[group] * (A @ B^T) + beta * C, where alpha[group] = scalings[l]
      is a *per-group* scalar built into meta.alpha and wired into the fusion's
      alpha_ptr_array path by args_from_options().
    * When base_output is supplied it becomes the residual source C with beta=1
      (D = scalings[l] * (A @ B^T) + base_output). base_output shares output's
      [num_tokens, 2N] layout, so the per-group byte offsets (meta.d_off) apply to
      it verbatim. Otherwise beta=0 and C is aliased to D (inert reads).

  The heavy CUTLASS type assembly + lifecycle live in the shared, reusable core
  (group_gemm_lora_launcher.hpp / common/group_gemm_types.hpp); the tile axis
  lives in gate_up_lora_b_fwd_types.hpp.
*/

#pragma once

#include <ATen/ATen.h>
#include <torch/all.h>

#include <optional>
#include <sycl/sycl.hpp>

#include "cutlass/cutlass.h"
#include "sycl/kernels/lora/common/group_gemm_types.hpp"
#include "sycl/kernels/lora/common/grouped_gemm_meta.hpp"
#include "sycl/kernels/lora/device/gate_up_lora_b_fwd_types.hpp"

namespace gate_up_lora_b_fwd_impl {

//----------------- runGateUpLoraBFwd (one-shot entry) -----------------------//
// High-level entry called from the per-(dtype, tile) .cpp files generated by
// GateUpLoraBFwdXe20.cmake. Builds the gate/up pointer-array grouped-GEMM
// metadata on device (2 * num_segments groups, including the per-group alpha
// buffer from scalings), assembles the CUTLASS Arguments via args_from_options(),
// and drives the shared GroupGemmLoraFwd launcher.
template <typename T, typename TileOpt>
inline void runGateUpLoraBFwd(
    const torch::Tensor& input_x,                     // [num_tokens, 2*K]  (K = max_rank)
    const torch::Tensor& gate_up_lora_b,              // [num_loras, 2*N, K]
    const torch::Tensor& seg_indptr_i32,              // [num_segments + 1]
    const torch::Tensor& weight_indices_i32,          // [num_segments]
    const torch::Tensor& scalings,                    // [num_loras] fp32 per-adapter scaling (lora_alpha / rank)
    torch::Tensor& output,                            // [num_tokens, 2*N]
    const std::optional<torch::Tensor>& base_output,  // [num_tokens, 2*N] residual C, or nullopt
    const int output_dim,                             // N (per-projection output width)
    const int num_segments,
    sycl::queue& queue) {
  namespace core = at::native::xpu;
  using Types = typename TileOpt::template Types<T>;

  constexpr int n_slices = 2;                                  // gate + up
  const int K = static_cast<int>(input_x.size(1) / n_slices);  // reduction dim == max_rank
  const int N = output_dim;
  const int N_total = n_slices * N;  // gate_up_lora_b.size(1)
  const int num_groups = n_slices * num_segments;
  const int64_t elem_bytes = static_cast<int64_t>(sizeof(T));
  const auto device = input_x.device();

  // Uniform gate/up column bands [0, N, 2N], built on device (arange * N) so no
  // output_offset argument is needed on the public API. gate and up share the
  // same width N, so the partition is regular.
  auto opt_i32 = torch::TensorOptions().dtype(torch::kInt32).device(device);
  auto output_offset_i32 = torch::arange(n_slices + 1, opt_i32) * N;

  // Per-group metadata + alpha (alpha[g] = scalings[weight_indices[g/2]]) built on
  // device (one thread per group) via the shared sliced build. gate/up packs 2
  // projections per segment: the input_x row is [num_tokens, 2*K] so A's leading
  // dim is 2*K and each projection p reads the K-wide column band at p*K; the
  // gate/up output bands come from output_offset. See common/grouped_gemm_meta.hpp.
  auto meta = core::build_grouped_gemm_meta(
      seg_indptr_i32,
      weight_indices_i32,
      N_total,
      K,
      num_segments,
      elem_bytes,
      device,
      queue,
      scalings,
      output_offset_i32,
      /*n_slices       =*/n_slices,
      /*a_row_stride   =*/static_cast<int64_t>(n_slices) * K,
      /*a_slice_stride =*/static_cast<int64_t>(K));

  auto a_ptrs = core::make_device_ptrs(input_x, meta.a_off, queue);
  auto b_ptrs = core::make_device_ptrs(gate_up_lora_b, meta.b_off, queue);
  auto d_ptrs = core::make_device_ptrs(output, meta.d_off, queue);

  // Per-group alpha as an array-of-pointers: entry g points at meta.alpha[g].
  // The grouped fusion reads *(alpha_ptr_array[l_coord]) with no stride -- the
  // per-group mechanism from upstream 04_bmg_grouped_gemm. Reuse make_device_ptrs:
  // base = meta.alpha, byte offsets = g * sizeof(float).
  auto opt_i64 = torch::TensorOptions().dtype(torch::kInt64).device(device);
  auto alpha_off = torch::arange(num_groups, opt_i64) * static_cast<int64_t>(sizeof(float));
  auto alpha_ptrs = core::make_device_ptrs(meta.alpha, alpha_off, queue);

  // Residual source C. base_output shares output's [num_tokens, 2N] layout, so
  // the per-group byte offsets (meta.d_off) apply verbatim. When absent, beta=0
  // and C is aliased to D so the (inert) C reads touch valid memory.
  const bool has_residual = base_output.has_value();
  const float beta = has_residual ? 1.0f : 0.0f;
  auto c_ptrs = has_residual ? core::make_device_ptrs(*base_output, meta.d_off, queue) : d_ptrs;

  // Build the CUTLASS Arguments (args_from_options). alpha is per-group via the
  // alpha_ptr_array (one pointer per group into meta.alpha); the scalar `alpha`
  // arg is therefore unused and passed as 1.0f.
  auto args = core::args_from_options<Types>(
      meta.problem_sizes,
      a_ptrs,
      b_ptrs,
      c_ptrs,
      d_ptrs,
      meta.stride_A,
      meta.stride_B,
      /*stride_C =*/meta.stride_D,
      meta.stride_D,
      num_groups,
      /*alpha           =*/1.0f,
      /*beta            =*/beta,
      /*alpha_ptr_array =*/alpha_ptrs);

  typename Types::Gemm launcher;

  cutlass::Status status = launcher.can_implement(args);
  TORCH_CHECK(
      status == cutlass::Status::kSuccess,
      "runGateUpLoraBFwd: can_implement failed: status=",
      cutlassGetStatusString(status));

  const size_t workspace_size = Types::Gemm::get_workspace_size(args);
  auto workspace_opts = torch::TensorOptions().dtype(torch::kUInt8).device(device);
  auto workspace = torch::empty({static_cast<int64_t>(workspace_size)}, workspace_opts);

  status = launcher.run(args, workspace.data_ptr(), queue);
  TORCH_CHECK(
      status == cutlass::Status::kSuccess, "runGateUpLoraBFwd: run failed: status=", cutlassGetStatusString(status));
}

}  // namespace gate_up_lora_b_fwd_impl
