/***************************************************************************************************
 * Copyright (C) 2026 Intel Corporation, All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/
/*!
  \file
  \brief The runSgemmLoraBFwd<T, TileOpt>() one-shot entry for LoRA-B forward.

  This runner unpacks a tile option tag (defined in sgemm_lora_b_fwd_types.hpp)
  into the template parameters of the shared pointer-array grouped-GEMM core and
  drives it end to end. It builds the grouped-GEMM metadata + pointer arrays on
  device and then drives the GroupGemmLoraFwd launcher.

  It differs from the A-fwd runner in the epilogue only:
    * D = alpha[seg] * (A @ B^T) + beta * C, where alpha[seg] = scalings[l] is a
      *per-segment* scalar (lora_alpha / rank folded in by the caller). This is
      built into meta.alpha by build_grouped_gemm_meta() and wired into the
      fusion's contiguous alpha_ptr path by args_from_options().
    * When base_output is supplied it becomes the residual source C with beta=1
      (D = scalings[l] * (A @ B^T) + base_output), otherwise beta=0 and C is
      aliased to D (inert reads), matching the A-fwd convention.

  The heavy CUTLASS type assembly + lifecycle and the device-side metadata build
  both live in the shared, reusable core (group_gemm_lora_launcher.hpp /
  common/grouped_gemm_meta.hpp); the tile axis lives in
  sgemm_lora_b_fwd_types.hpp.
*/

#pragma once

#include <ATen/ATen.h>
#include <torch/all.h>

#include <optional>
#include <sycl/sycl.hpp>

#include "cutlass/cutlass.h"
#include "sycl/kernels/lora/common/group_gemm_types.hpp"
#include "sycl/kernels/lora/common/grouped_gemm_meta.hpp"
#include "sycl/kernels/lora/device/sgemm_lora_b_fwd_types.hpp"

namespace sgemm_lora_b_fwd_impl {

//----------------- runSgemmLoraBFwd (one-shot entry) ------------------------//
// High-level entry called from the per-(dtype, tile) .cpp files generated by
// SGEMMLoraBFwdXe20.cmake. Builds the pointer-array grouped-GEMM metadata on
// device (including the per-segment alpha buffer from scalings), assembles the
// CUTLASS Arguments via args_from_options(), and drives the shared
// GroupGemmLoraFwd launcher.
template <typename T, typename TileOpt>
inline void runSgemmLoraBFwd(
    const torch::Tensor& input_x,               // [num_tokens, K]  (K = max_rank)
    const torch::Tensor& weights,               // [num_loras, output_dim, K]
    const torch::Tensor& seg_indptr_i32,        // [num_segments + 1]
    const torch::Tensor& weight_indices_i32,    // [num_segments]
    const torch::Tensor& scalings,              // [num_loras] fp32 per-adapter scaling (lora_alpha / rank)
    torch::Tensor& output,                      // [num_tokens, output_dim]
    const std::optional<torch::Tensor>& base_output,  // [num_tokens, output_dim] residual C, or nullopt
    const int output_dim,
    const int num_segments,
    sycl::queue& queue) {
  namespace core = at::native::xpu;
  using Types = typename TileOpt::template Types<T>;

  const int K = static_cast<int>(input_x.size(1));  // reduction dim == max_rank
  const int N = output_dim;                         // output columns
  const int64_t elem_bytes = static_cast<int64_t>(sizeof(T));
  const auto device = input_x.device();

  // Metadata + pointer arrays are built on device by SYCL kernels (one thread
  // per segment). Passing scalings materializes meta.alpha -- one alpha per
  // segment (alpha[s] = scalings[weight_indices[s]]). See grouped_gemm_meta.hpp.
  auto meta = core::build_grouped_gemm_meta(
      seg_indptr_i32, weight_indices_i32, N, K, num_segments, elem_bytes, device, queue, scalings);

  auto a_ptrs = core::make_device_ptrs(input_x, meta.a_off, queue);
  auto b_ptrs = core::make_device_ptrs(weights, meta.b_off, queue);
  auto d_ptrs = core::make_device_ptrs(output, meta.d_off, queue);

  // Per-segment alpha as an array-of-pointers: entry s points at meta.alpha[s].
  // The grouped fusion reads *(alpha_ptr_array[l_coord]) with no stride, which
  // is the per-group mechanism used by upstream 04_bmg_grouped_gemm. (The
  // strided alpha_ptr value-buffer path does not index per-group on the Xe
  // grouped epilogue -- it collapses to alpha[0] for every group.) Reuse
  // make_device_ptrs: base = meta.alpha, byte offsets = s * sizeof(float).
  auto opt_i64 = torch::TensorOptions().dtype(torch::kInt64).device(device);
  auto alpha_off = torch::arange(num_segments, opt_i64) * static_cast<int64_t>(sizeof(float));
  auto alpha_ptrs = core::make_device_ptrs(meta.alpha, alpha_off, queue);

  // Residual source C. base_output shares output's [num_tokens, output_dim]
  // layout, so the per-segment byte offsets (meta.d_off) apply verbatim. When
  // absent, beta=0 and C is aliased to D so the (inert) C reads touch valid
  // memory -- the A-fwd convention.
  const bool has_residual = base_output.has_value();
  const float beta = has_residual ? 1.0f : 0.0f;
  auto c_ptrs = has_residual ? core::make_device_ptrs(*base_output, meta.d_off, queue) : d_ptrs;

  // Build the CUTLASS Arguments (args_from_options) separately from launching.
  // alpha is per-segment via the alpha_ptr_array (one pointer per segment into
  // meta.alpha); the scalar `alpha` arg is therefore unused and passed as 1.0f.
  auto args = core::args_from_options<Types>(
      meta.problem_sizes,
      a_ptrs,
      b_ptrs,
      c_ptrs,
      d_ptrs,
      meta.stride_A,
      meta.stride_B,
      /*stride_C =*/meta.stride_D,
      meta.stride_D,
      num_segments,
      /*alpha           =*/1.0f,
      /*beta            =*/beta,
      /*alpha_ptr_array =*/alpha_ptrs);

  typename Types::Gemm launcher;

  cutlass::Status status = launcher.can_implement(args);
  TORCH_CHECK(
      status == cutlass::Status::kSuccess,
      "runSgemmLoraBFwd: can_implement failed: status=",
      cutlassGetStatusString(status));

  const size_t workspace_size = Types::Gemm::get_workspace_size(args);
  auto workspace_opts = torch::TensorOptions().dtype(torch::kUInt8).device(device);
  auto workspace = torch::empty({static_cast<int64_t>(workspace_size)}, workspace_opts);

  status = launcher.run(args, workspace.data_ptr(), queue);
  TORCH_CHECK(
      status == cutlass::Status::kSuccess, "runSgemmLoraBFwd: run failed: status=", cutlassGetStatusString(status));
}

}  // namespace sgemm_lora_b_fwd_impl
