/***************************************************************************************************
 * Copyright (C) 2026 Intel Corporation, All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/
/*!
  \file
  \brief Tile-configuration option tags + the runSgemmLoraAFwd<T, TileOpt>()
         one-shot entry for LoRA-A forward.

  This is the single place where a tile variant is registered: each option tag
  (e.g. LoraAFwdTileLarge) bundles the CUTE tile shape, the subgroup thread
  layout, the B layout, and the pipeline-stages count that the pointer-array
  grouped GEMM consumes. runSgemmLoraAFwd<T, TileOpt>() unpacks a tag into the
  template parameters of the shared grouped-GEMM core and drives it end to end.

  The heavy CUTLASS type assembly + lifecycle (can_implement / get_workspace_size
  / initialize / run) and the device-side metadata build both live in the shared,
  reusable core group_gemm_lora_launcher.hpp -- this file only layers the A-fwd
  tile axis on top of it, so the core stays intact for the other LoRA kernels
  (e.g. B-fwd) to reuse.

  Adding a new tile is a two-step change:
    1) Define a new option tag here.
    2) Register (tag name, C++ type) in SGEMMLoraAFwdXe20.cmake.
  The dtype dispatch in sgemm_lora_a_fwd.cpp then picks a tag per call.
*/

#pragma once

#include <ATen/ATen.h>
#include <torch/all.h>

#include <cute/tensor.hpp>
#include <sycl/sycl.hpp>

#include "cutlass/layout/matrix.h"
#include "sycl/kernels/lora/device/group_gemm_lora_launcher.hpp"

namespace sgemm_lora_a_fwd_impl {

//----------------- Tile / thread / staging option tags ----------------------//
// LayoutB is ColumnMajor for all tiles: the LoRA weight tensor is
// [num_loras, N, K] row-major, which is ColumnMajor when viewed as B in the
// A @ B^T grouped GEMM contract used here (the auto-selected copy atom
// free-transposes it).

// Canonical BMG grouped-GEMM tile (upstream 04_bmg_grouped_gemm):
//   TileShape       = 256 x 256 x 32
//   ThreadLayout    = 8 x 4 x 1   (32 subgroups / workgroup)
//   PipelineStages  = 2
struct LoraAFwdTileLarge {
  using TileShape = cute::Shape<cute::_256, cute::_256, cute::_32>;
  using ThreadLayout =
      cute::Layout<cute::Shape<cute::_8, cute::_4, cute::_1>, cute::Stride<cute::_4, cute::_1, cute::_0>>;
  using LayoutB = cutlass::layout::ColumnMajor;
  static constexpr int PipelineStages = 2;
};

//----------------- runSgemmLoraAFwd (one-shot entry) ------------------------//
// High-level entry called from the per-(dtype, tile) .cpp files generated by
// SGEMMLoraAFwdXe20.cmake. Builds the pointer-array grouped-GEMM metadata and
// dispatches to the shared grouped-GEMM core with the tile config from
// TileOpt and (alpha=1, beta=0) for the pure D = A @ B^T of LoRA-A.
template <typename T, typename TileOpt>
inline void runSgemmLoraAFwd(
    const torch::Tensor& input_x,
    const torch::Tensor& weights,
    const torch::Tensor& seg_indptr_i32,
    const torch::Tensor& weight_indices_i32,
    torch::Tensor& output,
    const int stack_num,
    const int max_rank,
    const int num_segments,
    sycl::queue& queue) {
  namespace core = at::native::xpu;

  const int K = static_cast<int>(input_x.size(1));  // input_dim
  const int N = stack_num * max_rank;               // output columns
  const int64_t elem_bytes = static_cast<int64_t>(sizeof(T));
  const auto device = input_x.device();

  // Metadata + pointer arrays are built on device by SYCL kernels (one thread
  // per segment) See group_gemm_lora_launcher.hpp.
  auto meta =
      core::build_grouped_gemm_meta(seg_indptr_i32, weight_indices_i32, N, K, num_segments, elem_bytes, device, queue);

  auto a_ptrs = core::make_device_ptrs(input_x, meta.a_off, queue);
  auto b_ptrs = core::make_device_ptrs(weights, meta.b_off, queue);
  auto d_ptrs = core::make_device_ptrs(output, meta.d_off, queue);

  // The shared core uses the modern (non-legacy) grouped path
  // (MainloopXeL1StagedGroup), which auto-selects the XMX DPAS MMA atom and all
  // gmem load/store/prefetch copy atoms per dtype.
  core::launch_group_gemm_lora_fwd<
      T,
      typename TileOpt::TileShape,
      typename TileOpt::ThreadLayout,
      typename TileOpt::LayoutB,
      TileOpt::PipelineStages>(
      queue,
      meta.problem_sizes,
      a_ptrs,
      b_ptrs,
      /*c_ptrs   =*/d_ptrs,  // beta=0 -> C reads are inert
      d_ptrs,
      meta.stride_A,
      meta.stride_B,
      /*stride_C =*/meta.stride_D,
      meta.stride_D,
      num_segments,
      /*alpha    =*/1.0f,
      /*beta     =*/0.0f);
}

}  // namespace sgemm_lora_a_fwd_impl
