set(FMHA_CHUNKPREFILL_HEAD_DIMS 64 96 128 192 256 512)

set(FMHA_CHUNKPREFILL_TEMPLATE
    "${CMAKE_CURRENT_SOURCE_DIR}/sycl/xe_fmha_fwd_chunkprefill_kernel.cpp.in")

set(FMHA_CHUNKPREFILL_TILED_Q_64 128)
set(FMHA_CHUNKPREFILL_TILED_KV_64 64)
set(FMHA_CHUNKPREFILL_NUM_SG_64 8)

set(FMHA_CHUNKPREFILL_TILED_Q_96 128)
set(FMHA_CHUNKPREFILL_TILED_KV_96 64)
set(FMHA_CHUNKPREFILL_NUM_SG_96 8)

set(FMHA_CHUNKPREFILL_TILED_Q_128 256)
set(FMHA_CHUNKPREFILL_TILED_KV_128 32)
set(FMHA_CHUNKPREFILL_NUM_SG_128 16)

set(FMHA_CHUNKPREFILL_TILED_Q_192 256)
set(FMHA_CHUNKPREFILL_TILED_KV_192 64)
set(FMHA_CHUNKPREFILL_NUM_SG_192 32)

set(FMHA_CHUNKPREFILL_TILED_Q_256 256)
set(FMHA_CHUNKPREFILL_TILED_KV_256 64)
set(FMHA_CHUNKPREFILL_NUM_SG_256 32)

set(FMHA_CHUNKPREFILL_TILED_Q_512 256)
set(FMHA_CHUNKPREFILL_TILED_KV_512 64)
set(FMHA_CHUNKPREFILL_NUM_SG_512 32)

foreach(HEAD_DIM ${FMHA_CHUNKPREFILL_HEAD_DIMS})
    set(TILED_Q ${FMHA_CHUNKPREFILL_TILED_Q_${HEAD_DIM}})
    set(TILED_KV ${FMHA_CHUNKPREFILL_TILED_KV_${HEAD_DIM}})
    set(NUM_SG ${FMHA_CHUNKPREFILL_NUM_SG_${HEAD_DIM}})

    set(GENERATED_FILE
        "${CMAKE_CURRENT_BINARY_DIR}/sycl/xe_fmha_fwd_chunkprefill_kernel_${HEAD_DIM}.cpp")
    configure_file(${FMHA_CHUNKPREFILL_TEMPLATE} ${GENERATED_FILE} @ONLY)
    list(APPEND device_cpp_common ${GENERATED_FILE})
endforeach()
