# Generate FMHA prefill kernel instantiation files.
# Each HEAD_DIM is compiled as a separate translation unit to parallelize
# and speed up compilation.

set(FMHA_PREFILL_HEAD_DIMS 64 72 96 128 192 256 512)

set(FMHA_PREFILL_TEMPLATE
    "${CMAKE_CURRENT_SOURCE_DIR}/sycl/xe_fmha_fwd_prefill_kernel.cpp.in")

# Per-HEAD_DIM tile shape parameters (TILED_Q, TILED_KV, NUM_SG)
set(FMHA_PREFILL_TILED_Q_64 128)
set(FMHA_PREFILL_TILED_KV_64 64)
set(FMHA_PREFILL_NUM_SG_64 8)

set(FMHA_PREFILL_TILED_Q_72 128)
set(FMHA_PREFILL_TILED_KV_72 64)
set(FMHA_PREFILL_NUM_SG_72 8)

set(FMHA_PREFILL_TILED_Q_96 128)
set(FMHA_PREFILL_TILED_KV_96 64)
set(FMHA_PREFILL_NUM_SG_96 8)

set(FMHA_PREFILL_TILED_Q_128 128)
set(FMHA_PREFILL_TILED_KV_128 64)
set(FMHA_PREFILL_NUM_SG_128 16)

set(FMHA_PREFILL_TILED_Q_192 256)
set(FMHA_PREFILL_TILED_KV_192 64)
set(FMHA_PREFILL_NUM_SG_192 32)

set(FMHA_PREFILL_TILED_Q_256 256)
set(FMHA_PREFILL_TILED_KV_256 64)
set(FMHA_PREFILL_NUM_SG_256 32)

set(FMHA_PREFILL_TILED_Q_512 256)
set(FMHA_PREFILL_TILED_KV_512 64)
set(FMHA_PREFILL_NUM_SG_512 32)

# Per-HEAD_DIM tile shape parameters for the NON-PAGED (contiguous ragged) KV
# path (TILED_Q_NP, TILED_KV_NP, NUM_SG_NP). These are kept as a separate set so
# the non-paged path can be tuned independently of the paged path. They are
# initialized to the paged values and can be adjusted later.
set(FMHA_PREFILL_TILED_Q_NP_64 128)
set(FMHA_PREFILL_TILED_KV_NP_64 64)
set(FMHA_PREFILL_NUM_SG_NP_64 8)

set(FMHA_PREFILL_TILED_Q_NP_72 256)
set(FMHA_PREFILL_TILED_KV_NP_72 64)
set(FMHA_PREFILL_NUM_SG_NP_72 16)

set(FMHA_PREFILL_TILED_Q_NP_96 256)
set(FMHA_PREFILL_TILED_KV_NP_96 64)
set(FMHA_PREFILL_NUM_SG_NP_96 16)

set(FMHA_PREFILL_TILED_Q_NP_128 256)
set(FMHA_PREFILL_TILED_KV_NP_128 32)
set(FMHA_PREFILL_NUM_SG_NP_128 16)

set(FMHA_PREFILL_TILED_Q_NP_192 256)
set(FMHA_PREFILL_TILED_KV_NP_192 64)
set(FMHA_PREFILL_NUM_SG_NP_192 32)

set(FMHA_PREFILL_TILED_Q_NP_256 256)
set(FMHA_PREFILL_TILED_KV_NP_256 64)
set(FMHA_PREFILL_NUM_SG_NP_256 32)

set(FMHA_PREFILL_TILED_Q_NP_512 256)
set(FMHA_PREFILL_TILED_KV_NP_512 64)
set(FMHA_PREFILL_NUM_SG_NP_512 32)

foreach(HEAD_DIM ${FMHA_PREFILL_HEAD_DIMS})
    set(TILED_Q ${FMHA_PREFILL_TILED_Q_${HEAD_DIM}})
    set(TILED_KV ${FMHA_PREFILL_TILED_KV_${HEAD_DIM}})
    set(NUM_SG ${FMHA_PREFILL_NUM_SG_${HEAD_DIM}})
    set(TILED_Q_NP ${FMHA_PREFILL_TILED_Q_NP_${HEAD_DIM}})
    set(TILED_KV_NP ${FMHA_PREFILL_TILED_KV_NP_${HEAD_DIM}})
    set(NUM_SG_NP ${FMHA_PREFILL_NUM_SG_NP_${HEAD_DIM}})

    set(GENERATED_FILE
        "${CMAKE_CURRENT_BINARY_DIR}/sycl/xe_fmha_fwd_prefill_kernel_${HEAD_DIM}.cpp")
    configure_file(${FMHA_PREFILL_TEMPLATE} ${GENERATED_FILE} @ONLY)
    list(APPEND device_cpp_common ${GENERATED_FILE})
endforeach()
